
include: package:lints/recommended.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
linter:
  rules:
    - avoid_dynamic_calls
    - avoid_type_to_string
    - no_runtimeType_toString

#analyzer:
#   exclude:
#     - path/to/excluded/files/**
