name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: APT update
      run: apt-get update
    - name: Install Firefox
      run: apt-get install -y firefox-esr xorg
    - name: WhoAmI
      run: whoami
    - name: Current DIR
      run: pwd && pwd >/tmp/test-dir.txt
    - name: Add user tester
      run: adduser --disabled-password tester
    - name: Pub Get
      run: su -c 'cd $(< /tmp/test-dir.txt) && pub get' tester
    - name: Run tests
      run: su -c 'DISPLAY=:0 cd $(< /tmp/test-dir.txt) && pub run test -p firefox' tester
