name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
      - uses: actions/checkout@v2
      - name: Dart version
        run: |
          dart --version
          uname -a
      - name: Current DIR
        run: pwd && pwd >/tmp/test-dir.txt
      - name: Add user tester
        run: adduser --disabled-password tester
      - name: Clean Project + chown tester
        run: |
          rm -rf .dart_tool .packages pubspec.lock
          chown -R tester:tester .
          ls -al
      - name: Tester Runner
        run: |
          echo "#/bin/bash\nset -x\nsu -c 'DISPLAY=:0 cd \$(< /tmp/test-dir.txt) && \$1' tester run '\$@'" > ./tester-run
          cat ./tester-run
          chmod 755 ./tester-run
      - name: Dart pub get
        run: ./tester-run 'dart pub get'
      - name: Dart format
        run: ./tester-run 'dart format -o none --set-exit-if-changed .'
      - name: Dart analyze
        run: ./tester-run 'dart analyze --fatal-infos --fatal-warnings .'
      - name: Run tests - VM
        run: ./tester-run 'dart test -p vm'
      - name: APT update
        run: apt-get update
      - name: Install Firefox
        run: apt-get install -y firefox-esr xorg
      - name: Run tests - Firefox
        run: ./tester-run 'dart test -p firefox'
