name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: APT update
      run: apt-get update
    - name: Install Firefox
      run: apt-get install -y firefox-esr xorg
    - name: Install dependencies
      run: pub get
    - name: WhoAmI
      run: whoami
    - name: Add user tester
      run: useradd tester && su tester
    - name: WhoAmI
      run: whoami
    - name: User 1001
      run: id -un 1001
    - name: Run tests
      run: su - $(id -un 1001) && pub run test -p firefox

