name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest
      options: --user 1001

    steps:
    - uses: actions/checkout@v2
    - name: APT update
      run: sudo apt-get update
    - name: Install Firefox
      run: sudo apt-get install -y firefox-esr xorg
    - name: Install dependencies
      run: pub get
    - name: Run tests
      run: pub run test -p firefox

