name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
      - uses: actions/checkout@v2
      - name: Dart version
        run: |
          dart --version
          uname -a
      - name: Current DIR
        run: pwd && pwd >/tmp/test-dir.txt
      - name: Add user tester
        run: adduser --disabled-password tester
      - name: Clean Project + chown tester
        run: |
          rm -rf .dart_tool .packages pubspec.lock
          chown -R tester:tester .
          ls -al
      - name: Tester Runner
        run: |
          echo "#/bin/bash\nsu -c 'DISPLAY=:0 cd \$(< /tmp/test-dir.txt) && \$@' tester \$1 \$@" > ./tester-run.sh
          cat ./tester-run.sh
          chmod 755 ./tester-run.sh
          ./tester-run.sh date
      - name: Pub Get test
        run: ./tester-run.sh dart pub get
      - name: Pub Get
        run: su -c 'cd $(< /tmp/test-dir.txt) && dart pub get' tester
      - name: dartfmt
        run: su -c 'cd $(< /tmp/test-dir.txt) && dart format -o none --set-exit-if-changed .' tester
      - name: dartanalyzer
        run: su -c 'cd $(< /tmp/test-dir.txt) && dart analyze --fatal-infos --fatal-warnings .' tester
      - name: Run tests VM
        run: su -c 'DISPLAY=:0 cd $(< /tmp/test-dir.txt) && dart test -p vm' tester
      - name: APT update
        run: apt-get update
      - name: Install Firefox
        run: apt-get install -y firefox-esr xorg
      - name: Run tests Firefox
        run: su -c 'DISPLAY=:0 cd $(< /tmp/test-dir.txt) && dart test -p firefox' tester
